# Generated by Django 4.1 on 2022-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("time_1", models.DateTimeField()),
                ("time_2", models.DateTimeField()),
                ("time_3", models.DateTimeField()),
                ("time_4", models.DateTimeField()),
                ("time_5", models.DateTimeField()),
                ("time_6", models.DateTimeField()),
                ("time_7", models.DateTimeField()),
                ("time_8", models.DateTimeField()),
                ("current_step", models.IntegerField(default=0)),
            ],
        ),
    ]
