# Generated by Django 4.1 on 2022-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0002_alter_item_time_1_alter_item_time_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="time_1",),
        migrations.RemoveField(model_name="item", name="time_2",),
        migrations.RemoveField(model_name="item", name="time_3",),
        migrations.RemoveField(model_name="item", name="time_4",),
        migrations.RemoveField(model_name="item", name="time_5",),
        migrations.RemoveField(model_name="item", name="time_6",),
        migrations.RemoveField(model_name="item", name="time_7",),
        migrations.RemoveField(model_name="item", name="time_8",),
        migrations.AddField(
            model_name="item",
            name="desc",
            field=models.CharField(default="", max_length=200),
        ),
    ]
